### ISSUE TITLE
ANSI sequences break URL matching

### ISSUE THREAD

**Issue by ibabushkin** [dequis/tmux-url-select#3]
In rare cases, an URL is partially colored or contains ANSI escape sequences for other reasons. For instance, if an IRC client highlights a nickname of a user present in the channel that happens to be an infix of the URL. In such cases the provided RegEx fails to match the URL. Though it may seem to be the right solution to avoid such cases by other means, I find it quite convenient at times, as the rate of false-positives is surprisingly low. I thus suggest to implement a way of avoiding such problems in `tmux-url-select`.

**Comment by nijotz** [comment]
I was having the same problem and just working around it with the smelly mouse.  Fixed it in PR #4

**Comment by ibabushkin** [comment]
Thanks for the quick action, everyone! Too bad my perl-foo is weak.
